server.port=1715

# Authentication
mock.auth.username=NetApp_Administrator
mock.auth.password=Netapp@123
mock.auth.token=mock-token-123

# Disable DB auto-configuration
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

# Optional Logging
logging.level.org.springframework.web=INFO
logging.level.com.example.netappmock=DEBUG


server.address=0.0.0.0